### PR TITLE
move edgeTransport to Depends to ensure it is attached, like other madrat packages

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**

### CODE REVIEW

**Comment by Loisel** [comment]
having this a an import can clutter the namespace (I'm afraid, e.g., of `data.table` vs `reshape2` and similar problems with conflicting function names). Is there a more elegant way or are we fine with this?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> having edgeTransport loaded via `Depends` can clutter the namespace (I'm afraid, e.g., of `data.table` vs `reshape2` and similar problems with conflicting function names). 

This does not produce any conflicts as is.  See `/p/tmp/pehl/preprocessing-remind/log-23330093.out`, which had `edgeTransport` and `data.table` attached:
  ```
other attached packages:
 [1] mrvalidation_2.37.12     mrmagpie_1.22.9          mrwater_1.1.34          
 [4] mrland_0.24.4            mrremind_0.123.7.9001    mrcommons_1.8.1         
 [7] mstools_0.2.4            mrdrivers_0.6.2          madrat_2.13.1           
[10] magclass_6.3.0           edgeTransport_0.6.4.9002 testthat_3.1.0          
[13] data.table_1.14.2 
```

> Is there a more elegant way or are we fine with this? 

Put `data.table` into `Imports` instead of `Depends` in `edgeTransport` and `importFrom` as needed `:p`

One dirty workaround would be to call a dummy function from ET before doing the `calcgenerateEDGEtransport`.

Not sure how that is supposed to work.
What does work however is calling `madrat::madratAttach('edgeTransport')` from `mrremind` explicitly.
```
Restarting R session...

> library(mrremind)
Loading required package: magclass
Loading required package: madrat
Loading required package: mrcommons
Loading required package: mrdrivers
Loading required package: mstools
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
> unique(getCalculations()$package)
[1] "madrat"    "mrdrivers" "mrcommons" "mrremind" 
> madrat::madratAttach('edgeTransport')
> unique(getCalculations()$package)
[1] "madrat"        "mrdrivers"     "mrcommons"     "mrremind"      "edgeTransport"
```

**Review by Loisel — APPROVED** [review]
I like.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> I like.

Then ~~like, share and subscribe~~ approve.

**Pull request merged**
