### PR TITLE
Included monitor calls to functions in edgeTransport and edgeTrpLib.

### PR DESCRIPTION
**Pull request by MariannaR**
This PR should avoid a situation like:

- `calcOutput('generateEDGEdata')`
- cache gets written
- change and update `edgeTrpLib` or `edgeTransport`
-  `calcOutput('generateEDGEdata')` again
- same cache gets loaded

-> changes of `edgeTrpLib` or `edgeTransport` are not loaded

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Well, that is brute-forcing it, making the changes to `edgeTransport` obsolete.  Just remember to update this whenever you add new functions to either `edgeTransport` or `edgeTrpLib`.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
For future reference:
```
$ for l in edgeTransport edgeTrpLib; do sed -n "s/^ *\([^\.][^ ]*\) *<- *function.*/\"#! @monitor $l:::\1\"/p" $( ls "$l"/R/*.R ); done
```

**Comment by Loisel** [comment]
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q is it clear what happens if you *monitor* functions that are not in the package namespace, e.g., `level2path`, which are defined inside other functions?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
When the respective package is attached/imported, they are monitored.  If not, madrat conplains _every single time you call it_.

**Pull request merged**
