### PR TITLE
Rm rhdf5

### PR DESCRIPTION
**Pull request by johanneskoch94**
I deleted the read- and convertGFED files, removed "rhdf5" and "ncdf4" from the DESCRIPTION file and ran lucode2::buildlibrary().

### CODE REVIEW

**Comment by giannou** [comment]
was this tested?

**Comment by johanneskoch94** [comment]
Well I just ran lucode2::buildlibrary(), I assume the tests passed no? Or do you mean another test?
In the meantime Michaja pushed a fix to his previous commit, so let me just adjust this pr ;)

**Comment by giannou** [comment]
I recommend running a test with the full input data preparation of REMIND

**Comment by johanneskoch94** [comment]
So fullREMIND() doesn't run, but the issue lies with the latest mrcommons version... I got to debug that now.

**Comment by giannou** [comment]
Now another bug appears.. looks like this is going to be a long day..

**Pull request merged**
