### PR TITLE
update historic CHA gas capacity values 2010-2020

### PR DESCRIPTION
**Pull request by robertpietzcker**
shift from gaschp to ngcc/ngt based on the IEA energy balances values on CHP electricity production vs non-CHP electricity production

### CODE REVIEW

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — COMMENTED** [review]
Should be a "source", instead of hard-coded data …

**Comment by robertpietzcker** [comment]
> 



> Should be a "source", instead of hard-coded data …

well - I am definitely not the expert on input data, but my understanding was that there is a trade-off - that adjusting very specific numbers is ok in the calcXXX scripts if it is on a small basis. Sources should be used once it is more like 50-5000 entries or so.

**Comment by fbenke-pik** [comment]
I am not sure if we have a strict policy requiring it to be a source (i.e. sth strict enough to reject the PR as it is). Since this is a modification and not newly introduced code, I am accepting now to not block potentially urgent updates. 

@LaviniaBaumstark Can you comment here what the general rule is?

**Review by fbenke-pik — APPROVED** [review]

**Comment by robertpietzcker** [comment]
I'll merge now, and if there is a clear statement that all such values should be put into a source, I can shift it afterwards.

**Pull request merged**
