### PR TITLE
update NDCs with cutoff data 2023-11-29

### PR DESCRIPTION
**Pull request by orichters**
update NDCs with cutoff data 2023-11-29, Includes those updates since March 31:
- [EU](https://unfccc.int/sites/default/files/NDC/2023-10/ES-2023-10-17%20EU%20submission%20NDC%20update.pdf)
- [Oman](https://unfccc.int/sites/default/files/NDC/2023-11/Oman%201st%20Update%20of%20the%202nd%20NDC%20-%20Optimized%20Size%20%281%29.pdf)
- [Brazil](https://unfccc.int/sites/default/files/NDC/2023-11/Brazil%20First%20NDC%202023%20adjustment.pdf)
- [Azerbaijan](https://unfccc.int/sites/default/files/NDC/2023-10/Second%20NDC_Azerbaijan_ENG_Final%20%281%29.pdf)
- [United Arab Emirates](https://unfccc.int/sites/default/files/NDC/2023-07/Third%20Update%20of%20Second%20NDC%20for%20the%20UAE_v15.pdf)
- [Kazakhstan](https://unfccc.int/sites/default/files/NDC/2023-06/12updated%20NDC%20KAZ_Gov%20Decree313_19042023_en_cover%20page.pdf)
- [Egypt](https://unfccc.int/sites/default/files/NDC/2023-06/Egypts%20Updated%20First%20Nationally%20Determined%20Contribution%202030%20%28Second%20Update%29.pdf)

Runs and cs2 are here: /p/tmp/rahelma/NDCupdate/remind-3.2/remind

- Note: EUR is based on regipol.

Changes: Factors compared to 2005 emissions

- 2030,LAM,2023_cond: 0.7622 -> 0.7519
- 2030,MEA,2023_cond: 1.2097 -> 0.9692
- 2050,REF,2023_cond: 0 -> 0.0917
- 2030,LAM,2023_uncond: 0.7809 -> 0.7703
- 2030,MEA,2023_uncond: 1.1233 -> 1.0695

2005 GHG emission share of countries with quantifyable emissions under NDC in particular region per target year

- 2050,REF,2023_cond: 0.0948 -> 0.1081

Strengthening of NDCs. Because a country with low ambitions has added a 2050 goal in REF, the coverage is extended, but the emission reduction goal for those with coverage is higher. That seems fine.

image
image

### CODE REVIEW

**Review by RahelMA — APPROVED** [review]
Thanks for the detailed description! The EU introduced sector target, in order to reach overall EU targets, could be interesting for `regipol`.

**Comment by Renato-Rodrigues** [comment]
By sector targets do you mean the ETS, ESR and LULUCF targets? Or are there more specific targets than those?

So far we never enforced the emission market targets in the NDC scenario, but if you want to include those in the NDC scenario definition, and by sector you mean the ETS and ESR targets, you can simply define then using emiMktTarget` switch and the model will adjust the EU CO2 price accordingly to reach those. Let me know if you want to do that and I could help on the configuration for the scenario config.

**Comment by RahelMA** [comment]
Thanks for clarifying, @Renato-Rodrigues! More specific targets are only set for **new cars and vans** and  **maritime emissions**. Thus, I guess there is no need for adjustments!

**Comment by Renato-Rodrigues** [comment]
LDV targets (cars and vans) are dealt within edge-t code and are included already at least in the more ambitious scenarios (Mix4).

It would be good to check if the current NDC runs respect these transport targets already and, if not, you could talk with the transport experts to adjust the edge-t scenario to respect those (I think it is Mix2 for the NDC).

**Pull request merged**
