### PR TITLE
Have industry track historic FE demand including 2020

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
Sometimes you just try something to see where it falls apart, and then it just works …

Updated industry electricity demand (tracks historic data to 2020 instead of 2015)
feel

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
And other `fety`s:
feso
feli
fega
feh2
fehe

**Review by robertpietzcker — APPROVED** [review]
Great!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Holding back for the current `mrremind` mess to untangle itself.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Well, first tests with REMIND are either outright data errors or lots of infeasibilities.  Won't merge this week, I guess.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Testing ae14c9b with remindmodel/remind@c24dd27b yields

- [x] `SSP2EU`
- [x] `SSP2EU-lowEn`
- [x] `SSP2EU-EU21`
- [x] `SSP1`
- [x] `SSP5`
- [x] `SDP_RC`: EEK value error
- [ ] `SSP2EU-NPi`: compilation error
- [ ] `SSP2EU-EU21-NPi`
- [ ] `SDP_MC`: EEK value error
- [ ] `SDP_EI`: EEK value error

The `NPi` stuff is not my department.  I will work on the `SDP`s and merge when they are fixed.

**Comment by robertpietzcker** [comment]
> The `NPi` stuff is not my department.

Great, thanks a lot!!!

can you post a path so I can have a look at the NPI?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Both `SDP_EI` and `SDP_MC` can be coaxed into solutions, but will need TLC during calibration.
@LaviniaBaumstark: to merge or not to merge?

**Comment by LaviniaBaumstark** [comment]
> Both `SDP_EI` and `SDP_MC` can be coaxed into solutions, but will need TLC during calibration. @LaviniaBaumstark: to merge or not to merge?

fine for me, I just merged new CES parameters and gdx files for SDP_EI and SDP_MC, maybe this will hold for your changes. And if not, I know what to so :-)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> How "dangerous" are those changes for the policy scenarios? Might we get a lot infes in our scenarios close to the next release version?

As dangerous as any input data change.

**Pull request merged**
