### PR TITLE
Add DEM_scenario column to EDGE-T inputs

### PR DESCRIPTION
**Pull request by Loisel**
Adds an additional dimension to EDGE-T inputs. This requires version 0.19.0 of EDGE-T to be installed.

### CODE REVIEW

**Review by LaviniaBaumstark — COMMENTED** [review]
this change requires adjustments in REMIND GAMS code to deal with the new results, right?

**Comment by Loisel** [comment]
yes, as soon as new inputdata is available, REMIND has to be updated as well. In fact there is a catch: we have to update edgeT to produce new inputdata with the new version of mrremind. Once we update edgeT, REMIND will stop working until we update REMIND. But if we update REMIND right away, it will break due to the unavailable input data.

**Comment by LaviniaBaumstark** [comment]
sure, please, just prepare REMIND changes so that the time of inconsistency is as short as possible. thanks

**Review by LaviniaBaumstark — APPROVED** [review]
nice that you introduced the function compress_magpie

**Review by LaviniaBaumstark — APPROVED** [review]

**Pull request merged**
